apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        mohanram634/jenkinsx-gke-gsm: true
        mohanram634/node-hello: true
        mohanram634/php: true
        mohanram634/ram: true
        mohanram634/simple-java-maven-app: true
        mohanram634/spring-boot: true
        mohanram634/testing: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        mohanram634/jenkinsx-gke-gsm: merge
        mohanram634/node-hello: merge
        mohanram634/php: merge
        mohanram634/ram: merge
        mohanram634/simple-java-maven-app: merge
        mohanram634/spring-boot: merge
        mohanram634/testing: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - mohanram634/jenkinsx-gke-gsm
        - mohanram634/node-hello
        - mohanram634/php
        - mohanram634/ram
        - mohanram634/simple-java-maven-app
        - mohanram634/spring-boot
        - mohanram634/testing
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - mohanram634/jenkinsx-gke-gsm
        - mohanram634/node-hello
        - mohanram634/php
        - mohanram634/ram
        - mohanram634/simple-java-maven-app
        - mohanram634/spring-boot
        - mohanram634/testing
      target_url: http://dashboard-jx.35.184.128.47.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
